CREATE TABLE public.core_institucion (
    "idInstitucion" integer NOT NULL,
    "nombreInstitucion" character varying(100) NOT NULL,
    "comunaInstitucion" character varying(50) NOT NULL,
    "esUniversidadInsti" boolean NOT NULL,
    "adscritoGratuidad" boolean NOT NULL,
    acreditacion integer NOT NULL,
    usuario_id integer NOT NULL,
    "webInstitucion" character varying(100) NOT NULL,
    "fotoInstitucion" character varying(100) NOT NULL
);


ALTER TABLE public.core_institucion OWNER TO "usuarioFuture";

--
-- TOC entry 235 (class 1259 OID 24742)
-- Name: core_institucion_idInstitucion_seq; Type: SEQUENCE; Schema: public; Owner: usuarioFuture
--

ALTER TABLE public.core_institucion ALTER COLUMN "idInstitucion" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."core_institucion_idInstitucion_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 241 (class 1259 OID 24764)
-- Name: core_parametros; Type: TABLE; Schema: public; Owner: usuarioFuture
--

CREATE TABLE public.core_parametros (
    "idParametros_id" integer NOT NULL,
    "comunaRelevancia" boolean NOT NULL,
    budget integer NOT NULL,
    gratuidad boolean NOT NULL,
    "acreditacionDeseado" integer NOT NULL,
    "esUniversidad" boolean NOT NULL,
    "puntajeNem" integer NOT NULL,
    carrera character varying(100) NOT NULL
);


ALTER TABLE public.core_parametros OWNER TO "usuarioFuture";

--
-- TOC entry 244 (class 1259 OID 40967)
-- Name: core_peticiones; Type: TABLE; Schema: public; Owner: usuarioFuture
--

CREATE TABLE public.core_peticiones (
    "idPeticiones" integer NOT NULL,
    asunto character varying(100) NOT NULL,
    "tipoPeticion" character varying(50) NOT NULL,
    mensaje text NOT NULL,
    "fechaPeticion" timestamp with time zone NOT NULL,
    usuario_id integer NOT NULL
);


ALTER TABLE public.core_peticiones OWNER TO "usuarioFuture";

--
-- TOC entry 243 (class 1259 OID 40966)
-- Name: core_peticiones_idPeticiones_seq; Type: SEQUENCE; Schema: public; Owner: usuarioFuture
--

ALTER TABLE public.core_peticiones ALTER COLUMN "idPeticiones" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."core_peticiones_idPeticiones_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 238 (class 1259 OID 24753)
-- Name: core_rol; Type: TABLE; Schema: public; Owner: usuarioFuture
--

CREATE TABLE public.core_rol (
    id_rol integer NOT NULL,
    nombre_rol character varying(30) NOT NULL
);


ALTER TABLE public.core_rol OWNER TO "usuarioFuture";

--
-- TOC entry 237 (class 1259 OID 24748)
-- Name: core_usuario; Type: TABLE; Schema: public; Owner: usuarioFuture
--

CREATE TABLE public.core_usuario (
    "idUsuario_id" integer NOT NULL,
    correo character varying(50) NOT NULL,
    "comunaUsuario" character varying(50) NOT NULL,
    rol_id integer NOT NULL
);


ALTER TABLE public.core_usuario OWNER TO "usuarioFuture";