# Generated by Django 5.2.5 on 2025-09-15 21:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Institucion',
            fields=[
                ('idInstitucion', models.AutoField(primary_key=True, serialize=False)),
                ('nombreInstitucion', models.CharField(max_length=100)),
                ('comunaInstitucion', models.CharField(max_length=50)),
                ('esUniversidadInsti', models.BooleanField(default=False)),
                ('costo', models.IntegerField()),
                ('adscritoGratuidad', models.BooleanField(default=False)),
                ('acreditacion', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('idUsuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('correo', models.CharField(max_length=50)),
                ('comunaUsuario', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id_rol', models.IntegerField(primary_key=True, serialize=False, verbose_name='0 para estudiante y 1 para institución, quiza 2 para admin')),
                ('nombre_rol', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('idCarrera', models.AutoField(primary_key=True, serialize=False)),
                ('nombreCarrera', models.CharField(max_length=100)),
                ('puntajeMinimo', models.IntegerField()),
                ('institucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.institucion')),
            ],
        ),
        migrations.CreateModel(
            name='Parametros',
            fields=[
                ('idParametros', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='core.usuario')),
                ('comunaRelevancia', models.BooleanField(default=False)),
                ('budget', models.IntegerField(default=0)),
                ('gratuidad', models.BooleanField(default=False)),
                ('acreditacionDeseado', models.IntegerField(default=0)),
                ('esUniversidad', models.BooleanField(default=False)),
                ('puntajeNem', models.IntegerField(default=0)),
                ('carrera', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='institucion',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.usuario'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='rol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.rol'),
        ),
    ]
