# Generated by Django 5.2.5 on 2025-09-16 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='institucion',
            name='costo',
        ),
        migrations.AddField(
            model_name='carrera',
            name='costo',
            field=models.IntegerField(default=0),
        ),
    ]
