# Generated by Django 5.2.5 on 2025-09-17 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_institucion_costo_carrera_costo'),
    ]

    operations = [
        migrations.AddField(
            model_name='institucion',
            name='webInstitucion',
            field=models.CharField(default='', max_length=100),
        ),
    ]
