# Generated by Django 5.2.5 on 2025-09-23 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_institucion_webinstitucion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='comunaUsuario',
            field=models.CharField(default='', max_length=50),
        ),
    ]
