# Generated by Django 5.2.5 on 2025-09-25 19:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_usuario_comunausuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='institucion',
            name='fotoInstitucion',
            field=models.ImageField(default='default_insti.png', upload_to=''),
        ),
        migrations.CreateModel(
            name='Peticiones',
            fields=[
                ('idPeticiones', models.AutoField(primary_key=True, serialize=False)),
                ('asunto', models.CharField(max_length=100)),
                ('tipoPeticion', models.CharField(max_length=50)),
                ('mensaje', models.TextField()),
                ('fechaPeticion', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.usuario')),
            ],
        ),
    ]
