# Generated by Django 5.2.5 on 2025-09-29 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_institucion_fotoinstitucion_peticiones'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parametros',
            name='puntajeNem',
            field=models.IntegerField(default=100),
        ),
    ]
