# Generated by Django 5.2.5 on 2025-09-29 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_parametros_acreditacionrelevancia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parametros',
            name='acreditacionRelevancia',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='parametros',
            name='budgetRelevancia',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='parametros',
            name='carreraRelevancia',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='parametros',
            name='comunaRelevancia',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='parametros',
            name='esUniversidadRelevancia',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='parametros',
            name='gratuidadRelevancia',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='parametros',
            name='puntajeNemRelevancia',
            field=models.BooleanField(default=True),
        ),
    ]
