# Generated by Django 5.2.5 on 2025-10-16 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_parametros_acreditacionrelevancia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='institucion',
            name='tipoInstitucion',
            field=models.CharField(default='', max_length=50),
        ),
    ]
