# Generated by Django 5.2.5 on 2025-10-16 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_institucion_tipoinstitucion'),
    ]

    operations = [
        migrations.AddField(
            model_name='peticiones',
            name='estadoPeticion',
            field=models.TextField(default='', max_length=50),
        ),
    ]
