# Generated by Django 5.2.5 on 2025-10-23 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_peticiones_estadopeticion'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrera',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='carrera',
            name='fecha_eliminado',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='institucion',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='institucion',
            name='fecha_eliminado',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='fecha_eliminado',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
