# Generated by Django 5.2.5 on 2025-11-04 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_carrera_activo_carrera_fecha_eliminado_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='institucion',
            name='esUniversidadInsti',
        ),
        migrations.RemoveField(
            model_name='parametros',
            name='esUniversidad',
        ),
        migrations.AddField(
            model_name='parametros',
            name='tipoBuscado',
            field=models.CharField(default='', max_length=50),
        ),
    ]
